---
title: "Business Card"
layout: default
---

<style>
  .business-card {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
    border: 2px solid #333;
    border-radius: 10px;
    text-align: center;
    font-family: Arial, sans-serif;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  }
  .photo {
    width: 100px;
    height: 100px;
    border-radius: 50%;
    margin: 10px auto;
  }
  .name {
    font-size: 24px;
    font-weight: bold;
    margin: 10px 0;
  }
  .contact {
    margin: 10px 0;
    font-size: 14px;
  }
  .link {
    color: #0066cc;
    text-decoration: none;
  }
  .experience {
    margin-top: 20px;
    text-align: left;
  }
</style>

<div class="business-card">
  <img class="photo" src="https://your-photo-url.jpg" alt="Your Photo">
  <div class="name">Oshean Lee</div>
  <div class="contact">
    <p>Email: <a class="link" href="mailto:your-email@example.com">your-email@example.com</a></p>
    <p>Phone: +123 456 7890</p>
    <p><a class="link" href="https://osheanlee.me/cv" target="_blank">View My CV</a></p>
  </div>
  <div class="experience">
    <h3>Past Work Experience</h3>
    <ul>
      <li><strong>Job Title 1</strong> - Company Name<br>Brief description of your role.</li>
      <li><strong>Job Title 2</strong> - Company Name<br>Brief description of your role.</li>
      <li><strong>Job Title 3</strong> - Company Name<br>Brief description of your role.</li>
    </ul>
  </div>
</div>
